"""
Django settings for my_project.
 
Generated by 'django-admin startproject' using Django 5.0.6.
 
For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: PROJECT_ROOT / 'subdir'.
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_TOKEN = 'django-insecure-8zxku*48==4ff=xl%2h&ng*jg7!h2wx8yy!b45g^sr!6aemjl&'

# SECURITY WARNING: don't run with debug turned on in production!
IS_DEBUG_MODE = True

ALLOWED_HOSTS_LIST = []

# Application definition

INSTALLED_APPS_LIST = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'noteapp',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE_LIST = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

URL_CONFIGURATION = 'my_project.urls'

TEMPLATE_SETTINGS = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION_PATH = 'my_project.wsgi.application'

CORS_ALLOWED_ORIGIN_LIST = [
    "http://localhost:5173",
    "http://localhost:5173",
]

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASE_SETTINGS = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PROJECT_ROOT / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

PASSWORD_VALIDATION_SETTINGS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]